### ISSUE TITLE
Tiles don't line up exactly

### ISSUE THREAD

**Issue by flarb** [brnkhy/MapzenGo#16] opened 2016-08-24 22:30 UTC
Perhaps it's because I'm not using LoadImage, but I've noticed that the tiles don't always line up against eachother--there's usually a gap in-between map tiles.
![seams](https://cloud.githubusercontent.com/assets/305261/17950364/a04f64a4-6a0f-11e6-9e56-35b295bee682.png)

**Comment by brnkhy** [comment] 2016-08-27 14:43
I believe this is a duplicate of #9 
I mean precision fixes should correct that as well

**Comment by brnkhy** [comment] 2016-09-05 19:19
this should be fixed with double precision commits

**Closed as completed by brnkhy** 2016-09-05 19:19 UTC
